### ISSUE TITLE
Shape of observation space does not agree.

### ISSUE THREAD

**Issue by smdsbz** [seungjaeryanlee/osim-rl-helper#5]
**Problem**  
The observation space shape specified in `DictToListFull.__init__()` is 347. However, its method `_dict_to_list()` is returning 350 features (with the updated environment).  

**Workaround**  
Simply change the `shape` keyword argument for `gym.spaces.Box()` to `(350,)` can hide the error.

**Comment by seungjaeryanlee** [comment]
Thank you for the report! It has been fixed now.
