### ISSUE TITLE
ModuleNotFoundError: No module named 'rl'

### ISSUE THREAD

**Issue by MinuteswithMetrics** [seungjaeryanlee/osim-rl-helper#7]
I get the syntax error below when I run  `./run.py TensorforcePPOAgent --train 1000`. I do not see a "rl" folder. 

Is this correct? 

```
from rl.agents import DDPGAgent

from rl.memory import SequentialMemory

from rl.random import OrnsteinUhlenbeckProcess
```

```
SyntaxError: invalid syntax

In [25]: !python ./run.py TensorforcePPOAgent --train 1000
Using TensorFlow backend.
Traceback (most recent call last):
  File "./run.py", line 22, in <module>
    from helper.baselines import *
  File "C:\Users\green\osim-rl-helper\helper\baselines\__init__.py", line 3, in
<module>
    from .keras import *
  File "C:\Users\green\osim-rl-helper\helper\baselines\keras\__init__.py", line
1, in <module>
    from .KerasDDPGAgent import KerasDDPGAgent
  File "C:\Users\green\osim-rl-helper\helper\baselines\keras\KerasDDPGAgent.py",
 line 5, in <module>
    from rl.agents import DDPGAgent
ModuleNotFoundError: No module named 'rl' 
```

**Comment by seungjaeryanlee** [comment]
Hello! Have you tried installing the `keras-rl` package?

**Comment by MinuteswithMetrics** [comment]
No, I haven't tried installing `keras-rl`. I will do that today.

**Comment by anbhimi** [comment]
Why is this issue still open? Is there any follow-up work?

**Comment by daniloromero** [comment]
I an getting this error in Colab
this is the output of the previous cell where I install keras-rl 
Requirement already satisfied: keras-rl in /root/.local/lib/python3.7/site-packages (0.4.2)
Requirement already satisfied: keras>=2.0.7 in /root/.local/lib/python3.7/site-packages (from keras-rl) (2.2.4)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from keras>=2.0.7->keras-rl) (1.15.0)
Requirement already satisfied: pyyaml in /root/.local/lib/python3.7/site-packages (from keras>=2.0.7->keras-rl) (5.3.1)
Requirement already satisfied: keras-applications>=1.0.6 in /root/.local/lib/python3.7/site-packages (from keras>=2.0.7->keras-rl) (1.0.8)
Requirement already satisfied: h5py in /root/.local/lib/python3.7/site-packages (from keras>=2.0.7->keras-rl) (2.10.0)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.7/dist-packages (from keras>=2.0.7->keras-rl) (1.4.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.7/dist-packages (from keras>=2.0.7->keras-rl) (1.1.2)
Requirement already satisfied: numpy>=1.9.1 in /root/.local/lib/python3.7/site-packages (from keras>=2.0.7->keras-rl) (1.18.5)

then after import keras-rl:


ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-9-54bc79f83e18> in <module>()
----> 1 import rl
      2 from PIL import Image
      3 import numpy as np
      4 import gym
      5 

ModuleNotFoundError: No module named 'rl'

**Comment by MennaEwas** [comment]
Try: pip install keras-rl2 if you were on colab

**Comment by umidyor** [comment]
> No, I haven't tried installing `keras-rl`. I will do that today.

yes, pip install keras-rl
this python packet solved this problem

**Comment by umidyor** [comment]
> I get the syntax error below when I run `./run.py TensorforcePPOAgent --train 1000`. I do not see a "rl" folder.
> 
> Is this correct?
> 
> ```
> from rl.agents import DDPGAgent
> 
> from rl.memory import SequentialMemory
> 
> from rl.random import OrnsteinUhlenbeckProcess
> ```
> 
> ```
> SyntaxError: invalid syntax
> 
> In [25]: !python ./run.py TensorforcePPOAgent --train 1000
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "./run.py", line 22, in <module>
>     from helper.baselines import *
>   File "C:\Users\green\osim-rl-helper\helper\baselines\__init__.py", line 3, in
> <module>
>     from .keras import *
>   File "C:\Users\green\osim-rl-helper\helper\baselines\keras\__init__.py", line
> 1, in <module>
>     from .KerasDDPGAgent import KerasDDPGAgent
>   File "C:\Users\green\osim-rl-helper\helper\baselines\keras\KerasDDPGAgent.py",
>  line 5, in <module>
>     from rl.agents import DDPGAgent
> ModuleNotFoundError: No module named 'rl' 
> ```

You are don't install keras-rl2
You should ### **pip install keras-rl**
